language: python
dist: xenial
sudo: required

python:
  - "2.7"
  # - "3.3"
  # - "3.4"
  # - "3.5"
  # - "3.6"
  # - "3.7-dev"
  # - "pypy"
  # - "pypy-5.3.1"

matrix:
    allow_failures:
        - python: 3.7-dev

# command to install dependencies
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y build-essential ca-certificates curl cmake libc6-dev libevent-dev libffi-dev libgit2-dev libnacl-dev libssl-dev libxml2-dev libxslt1-dev libzmq3-dev openssl pkg-config python-pip python2.7 python2.7-dev

env:
  - LIBGIT2_VERSION=0.26.0

install:
  - python setup.py build sdist
  - pip install -r development.txt
  - pip install -U pip
  - cd /tmp && wget -q https://github.com/libgit2/libgit2/archive/v${LIBGIT2_VERSION}.tar.gz && tar xzvf v${LIBGIT2_VERSION}.tar.gz && cd libgit2-${LIBGIT2_VERSION} && mkdir -p build/install && cd build && cmake -DCMAKE_INSTALL_PREFIX:PATH=/usr ..  cmake -DCMAKE_INSTALL_PREFIX:PATH=/usr --build . make install

# command to run tests
script: nosetests

# automated pypi releases
deploy:
  provider: pypi
  user: gabrielfalcao
  password:
    secure: E5KbnpQau7jv/mpHWAs19Y5zBaOHyBXRCGAsTS0S5lEOp/g8EEbjyt5rL7lcIeFAYarIds719BktC5iO+1AQbXOYicS5vDfiVRdLaJ5HPA4v6zyyQzwadFKSqE1Tv11AG9xkFDfBEPLTQmSrpI5cJIY5UoafDnMZe4CbLVETTw8=
  on:
    branch: master
    tags: true
  distributions: sdist bdist_wheel
