language: python
dist: xenial
sudo: required

services:
  - docker

python:
  - "2.7"
  # - "3.3"
  # - "3.4"
  # - "3.5"
  # - "3.6"
  # - "3.7-dev"
  # - "pypy"
  # - "pypy-5.3.1"

matrix:
    allow_failures:
        - python: 3.7-dev

# command to install dependencies
install:
  - docker build -t gitgraph .

env:
  - LIBGIT2_VERSION=0.26.0

script: docker run -v .:/gitgraph gitgraph nosetests

# automated pypi releases
deploy:
  provider: pypi
  user: gabrielfalcao
  password:
    secure: E5KbnpQau7jv/mpHWAs19Y5zBaOHyBXRCGAsTS0S5lEOp/g8EEbjyt5rL7lcIeFAYarIds719BktC5iO+1AQbXOYicS5vDfiVRdLaJ5HPA4v6zyyQzwadFKSqE1Tv11AG9xkFDfBEPLTQmSrpI5cJIY5UoafDnMZe4CbLVETTw8=
  on:
    branch: master
    tags: true
  distributions: sdist bdist_wheel
