language: python
dist: xenial
sudo: false
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7-dev"
  - "pypy"
  - "pypy-5.3.1"

matrix:
    allow_failures:
        - python: 3.7-dev

# command to install dependencies
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libgit2-dev libffi-dev

install:
  - python setup.py build sdist
  - pip install -r development.txt

# command to run tests
script: nosetests

# automated pypi releases
deploy:
  provider: pypi
  user: gabrielfalcao
  password:
    secure: E5KbnpQau7jv/mpHWAs19Y5zBaOHyBXRCGAsTS0S5lEOp/g8EEbjyt5rL7lcIeFAYarIds719BktC5iO+1AQbXOYicS5vDfiVRdLaJ5HPA4v6zyyQzwadFKSqE1Tv11AG9xkFDfBEPLTQmSrpI5cJIY5UoafDnMZe4CbLVETTw8=
  on:
    branch: master
    tags: true
  distributions: sdist bdist_wheel
